masterPassword: 'password'
accounts:
  - name: 'Playground'
    serverUrl: 'playground-lnd:10009'
    macaroonPath: '/etc/lnd/data/chain/bitcoin/signet/admin.macaroon'
    certificatePath: '/etc/lnd/tls.cert'
    
