name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for LND pointed to Playground signet
      run: |
        cd lnd-signet
        echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/plebnet-playground/playground-lnd --tag playground-lnd
        docker push ghcr.io/plebnet-playground/playground-lnd
        cd ..
    - name: Build the Docker image for c-ligthning pointed to Playground signet
      run: |
        cd clightning-signet
        echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/plebnet-playground/playground-clightning --tag playground-clightning
        docker push ghcr.io/plebnet-playground/playground-clightning
        cd ..
    - name: Build the Docker image for bitcoind pointed to Playground signet
      run: |
        cd bitcoin-signet
        echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/plebnet-playground/playground-bitcoind --tag playground-bitcoind --build-arg ARCH=x86_64-linux-gnu
        docker push ghcr.io/plebnet-playground/playground-bitcoind
        cd ..
    - name: Build the Docker image for tor used in Playground signet
      run: |
        cd tor
        echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/plebnet-playground/playground-tor --tag playground-tor
        docker push ghcr.io/plebnet-playground/playground-tor
        cd ..
    - name: Build the Docker image for Thunderhub used in Playground signet
      run: |
        cd thub
        echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/plebnet-playground/playground-thub --tag playground-thub
        docker push ghcr.io/plebnet-playground/playground-thub
        cd ..